version: "3.6"

networks:
  tb-network:
    driver: bridge

services:
  tb-postgres:
    container_name: tb-postgres
    restart: always
    build:
      context: ./devops/postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./devops/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
      - ${FILESTORE}/logs/postgres:/var/log/postgresql
    networks:
      - tb-network

  tb-backend:
    restart: always
    container_name: tb-backend
    image: tb-backend:latest
    build:
      context: ./backend
      dockerfile: ./TextBooker.Api/Dockerfile
    ports:
      - 2055:80
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
      DB_CONNECTION_STRING: 'Server=tb-postgres;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};'
      LOKI_URL: 'http://loki:3100'
    networks:
      - tb-network
    links:
      - tb-postgres
      - loki
    depends_on:
      - tb-postgres

  tb-frontend: 
    restart: always
    container_name: tb-frontend
    image: tb-frontend:latest
    build:
      context: ./frontend
    ports:
      - 2050:2050
    environment:
      - NODE_ENV=production
      - VUE_APP_HOST=/api
    networks:
      - tb-network

  tb-nginx:
    container_name: tb-nginx
    restart: always
    image: nginx:1.16.0-alpine
    volumes:
      - ./devops/nginx/html:/var/www/html/errors
      - ./devops/nginx/page.conf:/etc/nginx/page.conf
      - ./devops/nginx/error_pages.conf:/etc/nginx/error_pages.conf
      - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${FILESTORE}/logs/nginx:/var/log/nginx
    ports:
      - 80:80
    networks:
      - tb-network
    links:
      - tb-backend
      - tb-frontend

  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - tb-network
    labels:
      org.label-schema.group: "monitoring"

  node-exporter:
    image: prom/node-exporter:v1.0.0-rc.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - tb-network
    labels:
      org.label-schema.group: "monitoring"

  nginx-exporter:
    restart: unless-stopped
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:0.7.0
    environment:
      - SCRAPE_URI=http://tb-nginx/nginx_status
      - TELEMETRY_PATH=/metrics
      - NGINX_RETRIES=10
    networks:
      - tb-network
    links:
      - tb-nginx
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    labels:
      org.label-schema.group: "monitoring"

  postgres-exporter:
    container_name: postgres-exporter
    image: wrouesnel/postgres_exporter:v0.8.0
    restart: unless-stopped
    environment:
      - DATA_SOURCE_URI=tb-postgres/${POSTGRES_DB}?sslmode=disable
      - DATA_SOURCE_USER=${POSTGRES_USER}
      - DATA_SOURCE_PASS=${POSTGRES_PASSWORD}
    networks:
      - tb-network
    depends_on:
      - tb-postgres
    links:
      - tb-postgres
    labels:
      org.label-schema.group: "monitoring"

  prometheus:
    restart: always
    container_name: prometheus
    image: prom/prometheus:v2.18.1
    volumes:
      - ./devops/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - tb-backend
      - cadvisor
      - postgres-exporter
      - nginx-exporter
      - node-exporter
    networks:
      - tb-network
    labels:
      org.label-schema.group: "monitoring"
      
  loki:
    image: grafana/loki:master-2739551
    restart: always
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./devops/loki:/etc/loki
      - loki-data:/tmp/loki/
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - tb-network

  grafana:
    restart: always
    container_name: grafana
    image : grafana/grafana:6.4.4
    depends_on: 
      - prometheus
      - loki
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./devops/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
    networks:
      - tb-network
    labels:
      org.label-schema.group: "monitoring"

  promtail:
    image: grafana/promtail:master-2739551
    container_name: promtail
    restart: always
    volumes:
      - ./devops/loki:/etc/promtail
      - ${FILESTORE}/logs/nginx:/var/log/nginx
      - ${FILESTORE}/logs/postgres:/var/log/postgresql
    command: -config.file=/etc/promtail/loki-promtail-config.yml
    links:
      - loki
    networks:
      - tb-network

volumes:
  db-data:
  prometheus-data:
  loki-data:
  grafana-data: