global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'TextBooker'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
        - tb-backend:80
        - cadvisor:8080
        - postgres-exporter:9187
        - nginx-exporter:9113
        - node-exporter:9100