FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ARG Configuration=Release

WORKDIR /src

COPY . .

WORKDIR /src/TextBooker.DataAccess

ENV PATH="${PATH}:/root/.dotnet/tools"
RUN export PATH="$PATH:/root/.dotnet/tools"

RUN dotnet tool install --global dotnet-ef --version 3.1.4

CMD dotnet ef database update