version: '3.6'

networks:
  textbooker:
    driver: bridge

services:
  postgres:
    container_name: postgres
    build:
      context: ./devops/docker/postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./devops/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    networks:
      - textbooker

  db-migrations:
    image: db-migrations:latest
    container_name: db-migrations
    build:
      context: ./backend
      dockerfile: ../devops/docker/backend/Dockerfile.Migrations
    environment:
      DB_CONNECTION_STRING: 'Server=postgres;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};'
    depends_on:
      - postgres
    networks:
      - textbooker
    links:
      - postgres

  backend:
    image: backend:latest
    container_name: backend
    build:
      context: ./backend
      dockerfile: ../devops/docker/backend/Dockerfile
    restart: always
    ports:
      - 2055:80
    env_file:
      - ./.env
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
      DB_CONNECTION_STRING: 'Server=postgres;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};'
      LOKI_URL: 'http://loki:3100'
      FILESTORE_BASEPATH: '/filestore'
    volumes:
      - ./devops/filestore/themes:/filestore/themes
      - /filestore:/filestore
    depends_on:
      - postgres
      - db-migrations
    networks:
      - textbooker
    links:
      - postgres
      - loki

  frontend:
    image: frontend:latest
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ../devops/docker/frontend/Dockerfile
    restart: always
    ports:
      - 2050:2050
    environment:
      - NODE_ENV=production
      - VUE_APP_HOST=/api
    networks:
      - textbooker

  nginx:
    image: nginx:1.18-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./devops/nginx/page.conf:/etc/nginx/page.conf
      - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx/
      - /filestore/sites:/var/www/sites/
    ports:
      - 80:80
    networks:
      - textbooker
    links:
      - backend
      - frontend

  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - textbooker
    labels:
      org.label-schema.group: 'monitoring'

  node-exporter:
    image: prom/node-exporter:v1.0.0-rc.1
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - textbooker
    labels:
      org.label-schema.group: 'monitoring'

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.7.0
    container_name: nginx-exporter
    restart: always
    environment:
      - SCRAPE_URI=http://nginx/nginx_status
      - TELEMETRY_PATH=/metrics
      - NGINX_RETRIES=10
    networks:
      - textbooker
    links:
      - nginx
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
    labels:
      org.label-schema.group: 'monitoring'

  postgres-exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    container_name: postgres-exporter
    restart: always
    environment:
      - DATA_SOURCE_URI=postgres/${POSTGRES_DB}?sslmode=disable
      - DATA_SOURCE_USER=${POSTGRES_USER}
      - DATA_SOURCE_PASS=${POSTGRES_PASSWORD}
    networks:
      - textbooker
    depends_on:
      - postgres
    links:
      - postgres
    labels:
      org.label-schema.group: 'monitoring'

  prometheus:
    image: prom/prometheus:v2.18.1
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./devops/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - textbooker
    links:
      - backend
      - cadvisor
      - postgres-exporter
      - nginx-exporter
      - node-exporter
    labels:
      org.label-schema.group: 'monitoring'

  loki:
    image: grafana/loki:master-2739551
    container_name: loki
    restart: always
    ports:
      - 3100:3100
    volumes:
      - ./devops/loki:/etc/loki
      - loki-data:/tmp/loki/
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - textbooker

  grafana:
    image: grafana/grafana:6.4.4
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./devops/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
    networks:
      - textbooker
    depends_on:
      - prometheus
      - loki
    labels:
      org.label-schema.group: 'monitoring'

  promtail:
    image: grafana/promtail:master-2739551
    container_name: promtail
    restart: always
    volumes:
      - ./devops/loki:/etc/promtail
      - db-logs:/var/log/postgresql
      - /var/log/nginx:/var/log/nginx
    command: -config.file=/etc/promtail/loki-promtail-config.yml
    links:
      - loki
    networks:
      - textbooker

volumes:
  db-logs:
  db-data:
  prometheus-data:
  loki-data:
  grafana-data:
  filestore:
